// Data.js
export const CardData = [
  {
    id: 1,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: true,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 22.png",
  },
  {
    id: 2,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: false,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 35.png",
  },
  {
    id: 3,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: true,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 33.png",
  },
  {
    id: 4,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: true,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 32.png",
  },
  {
    id: 5,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: false,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 28.png",
  },
  {
    id: 6,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: true,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 34.png",
  },
  {
    id: 7,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: true,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 35.png",
  },
  {
    id: 8,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: false,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 23.png",
  },
  {
    id: 9,
    title: "GoPro HERO6 4K Action Camera",
    subtitle: "Black",
    currentPrice: "$99.50",
    originalPrice: "$1128.00",
    rating: 7.5,
    brand: "GoPro",
    verified: true,
    imgSrc: "public/Assets/Pages/Products/Product Cards/image 33.png",
  },
];
